### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by NickImpact** [NickImpact/Bidoof-Unleashed#1]
- [x] Gyms can have the same name/ID - Need to implement a check
- [x] Fix issue where leaders are unable to accept challenges (Might be incorrect return message)
- [x] Additional Commands
  - [x] Add Pokemon Spec - Add the spec of a pokemon to the available pool
  - [x] Gym editing
  - [x] Commands to add rules and clauses
  - [x] Help command that actually works
- [x] Actually hook up gym states to the running instance of a Gym
- [x] Reload options, because everyone loves these for some reason
- [x] SQL Join error - I have no idea why on this one
